### ISSUE TITLE
Error appears after patching 18 of 23..

### ISSUE THREAD

**Issue by mshmsh94** [LiamKarlMitchell/AnrinchTwelveSkyLauncher#26]
![untitled](https://cloud.githubusercontent.com/assets/15491343/10860928/8eca51b6-7f79-11e5-93d7-69ec328ddd10.JPG)

its stuck at 18 and then this message appear

**Comment by LiamKarlMitchell** [comment]
there was a patch that fixed this already.

im surprised people didn't get it somehow.

If you download this file and replace the one you have in the launcher/js directory it should fix it.
https://github.com/LiamKarlMitchell/AnrinchTwelveSkyLauncher/blob/master/Launcher/js/HTTPFileProgressDownload.js

**Comment by LiamKarlMitchell** [comment]
Although if its already applied, it cpi;d also be caused by a curropted/interupted download hmm.

**Comment by pongqlwn** [comment]
Hello there,

The fix you posted above didn't solve this issue on my end, so I proceeded to figure out the process on my own.
18/info.txt on the patch server displays fine and pretty much looks identical to the others. Then I fished the zip file manually from the server. It opens and extracts just fine but took around 30 minutes to download, so the launcher might just be timing out.

Cheers.

**Comment by titopr** [comment]
Hello people, I have the same error, update stuck at 18 and came a game error

**Comment by LiamKarlMitchell** [comment]
@Linvplz thanks, for researching into it.
The patch is unfortunatly massive.

It might be possible its timing out, although im not aware of some default time out whilst its still receiving data. One problem we had that showed that message was trying to read the zip before it was fully saved to disk. Which is what the fix i said above should fix.

So maybe it is being caused by some other thing.

**Comment by pongqlwn** [comment]
@LiamKarlMitchell You're welcome. Sorry about my rather unconclusive results, I just don't know where else to look.

If it really was timing out for some reason though, one possible workaround could be to split the patch into two or three parts and move all subsequent patches further up. Yeah, it would unnecessarily re-download the last few patches to everybody else, but they're pretty small anyway.
Then again, patch 21 takes pretty long on my end too, yet always successfully finishes, so it might be something else. (Maybe it would have failed too prior to your fix)

Best wishes! You've done an awesome work thus far.

**Comment by LiamKarlMitchell** [comment]
Yeah, one option would be not have such a big as patch. And offer an alternative way to patch / new installer.
